### PR TITLE
Deduplicate trackers, fixes #4

### LINKED ISSUE #4: duplicate metrics collected on trackers
I get this error:

```
An error has occurred during metrics collection:

96 error(s) occurred:
* collected metric transmission_torrent_downloads_total label:<name:"id" value:"155" > label:<name:"name" value:"dns-registration-2011-to-2016.csv.xz" > label:<name:"tracker" value:"udp://open.demonii.com:1337" > gauge:<value:-1 >  was collected before with the same name and label values
* collected metric transmission_torrent_leechers label:<name:"id" value:"155" > label:<name:"name" value:"dns-registration-2011-to-2016.csv.xz" > label:<name:"tracker" value:"udp://open.demonii.com:1337" > gauge:<value:-1 >  was collected before with the same name and label values
* collected metric transmission_torrent_seeders label:<name:"id" value:"155" > label:<name:"name" value:"dns-registration-2011-to-2016.csv.xz" > label:<name:"tracker" value:"udp://open.demonii.com:1337" > gauge:<value:-1 >  was collected before with the same name and label values
...
```

Which seems to be caused by duplicate trackers on torrents. If I do a request on the RPC then it shows that there actually are duplicate trackers on the torrent and transmission doesn't deduplicate or ignore them.

### PR DESCRIPTION
**Pull request by myfreeweb**
I'm not actually sure whether we need to sum up the DownloadCount or just ignore the duplicates…

### CODE REVIEW

**Comment by metalmatze** [comment]
So this fix is just about the download count, which was previously the sum of all trackers?

**Comment by myfreeweb** [comment]
It's about duplicate entries in `TrackerStats`, by using a hash map the entries are deduplicated and the #4 error is prevented

**Comment by metalmatze** [comment]
Alright, I can recreate the issue on my machine now, thanks for the help.

I have a lot of counters that are `-1`. I think we should update the PR to set those to `0`.

```
transmission_torrent_downloads_total{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker.zer0day.to:1337"} -1
transmission_torrent_downloads_total{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker1.wasabii.com.tw:6969"} -1
...
transmission_torrent_leechers{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker.zer0day.to:1337"} -1
transmission_torrent_leechers{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker1.wasabii.com.tw:6969"} -1
...
transmission_torrent_seeders{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker.zer0day.to:1337"} -1
transmission_torrent_seeders{id="2",name="pwned-passwords-2.0.txt.7z",tracker="udp://tracker1.wasabii.com.tw:6969"} -1
```

Otherwise this looks good to me.

**Comment by jonnrb** [comment]
I didn’t notice this until now, but I think the dups are due to udp and http trackers with the same fqdn in one torrent. Should those be treated as the same tracker in the stats? Might it be a good future improvement to add a label for the protocol used?

**Comment by metalmatze** [comment]
I'll merge this and then do some more testing with it. Thanks and sorry for the huge delay!

**Pull request merged**
